Repository AY2021S1-CS2103T-F12-1/tp, pull requests merged in 2020-10, with the labels that each got.

#42 Tutorial adding command
  README.md
Labels: wontfix

#83 Update CliSyntax to match HelloFile
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: priority.High

#82 docs/SettingUp.md: Rectify link to IDEA guide (#50)
  docs/SettingUp.md
Labels: priority.Low, type.Task

#91 Add OpenCommand and OpenCommandParser
  src/main/java/seedu/address/logic/commands/OpenCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/OpenCommandParser.java
  src/main/java/seedu/address/model/tag/FileAddress.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/commands/ModelStubAcceptingTagAdded.java
  src/test/java/seedu/address/logic/commands/ModelStubWithAddressBook.java
  src/test/java/seedu/address/logic/commands/ModelStubWithTag.java
  src/test/java/seedu/address/logic/commands/OpenCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/OpenCommandTest.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/OpenCommandParserTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TagBuilder.java
  src/test/java/seedu/address/testutil/TypicalTags.java
  src/test/java/seedu/address/testutil/cs2101.bat
  src/test/java/seedu/address/testutil/cs2101.sh
  src/test/java/seedu/address/testutil/cs2103.bat
  src/test/java/seedu/address/testutil/cs2103.sh
  src/test/java/seedu/address/testutil/testFile.bat
  src/test/java/seedu/address/testutil/testFile.sh
Labels: priority.High

#94 Resolve a bug in the tag command
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
Labels: priority.Medium

#118 Update FindCommand to match characters instead of words
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/tag/TagNameContainsCharPredicate.java
  src/main/java/seedu/address/model/tag/TagNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/ThemeWindow.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
Labels: priority.Medium

#166 Update CdCommand to varify if parsed address is valid or not
  src/main/java/seedu/address/logic/commands/CdCommand.java
Labels: type.Bug

#183 Add VersionedAddressBook and test classes
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/model/VersionedAddressBookTest.java
Labels: priority.High

#189 Add more testing
  build.gradle
  src/main/java/seedu/address/logic/commands/LabelCommand.java
  src/main/java/seedu/address/logic/commands/OpenCommand.java
  src/main/java/seedu/address/logic/commands/RetagCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/model/explorer/CurrentPath.java
  src/main/java/seedu/address/model/explorer/FileList.java
  src/main/java/seedu/address/model/tag/FileAddress.java
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CdCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/LabelCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ModelStubWithCurrentPath.java
  src/test/java/seedu/address/logic/commands/ModelStubWithTagAndTaglist.java
  src/test/java/seedu/address/logic/commands/OpenCommandTest.java
  src/test/java/seedu/address/logic/commands/RetagCommandTest.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/address/model/tag/AddressTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: priority.Medium

#194 Update OpenCommand to use Label
  src/main/java/seedu/address/logic/commands/OpenCommand.java
  src/main/java/seedu/address/logic/parser/OpenCommandParser.java
  src/main/java/seedu/address/model/tag/FileAddress.java
  src/main/java/seedu/address/model/tag/TagLabelEqualsKeywordPredicate.java
  src/test/java/seedu/address/logic/commands/OpenCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/OpenCommandTest.java
  src/test/java/seedu/address/logic/parser/OpenCommandParserTest.java
  src/test/java/seedu/address/model/tag/AddressTest.java
  src/test/java/seedu/address/model/tag/TagLabelEqualsKeywordPredicateTest.java
  src/test/java/seedu/address/model/tag/TagNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/tag/TagNameEqualsKeywordPredicateTest.java
Labels: priority.High
